name: "gosh"

services:
  server:
    image: gosh:dev
    container_name: gosh
    build:
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: ./
          ignore:
            - bin/
            - Makefile
    ports:
      - "23234:23234"
    environment:
      - TERM=tmux-256color
