FROM golang:1.22.3-alpine

WORKDIR /src

COPY go.mod go.sum ./

RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o ./main ./cmd/server/main.go

EXPOSE 23234

ENTRYPOINT [ "./main" ]
